inpath: "../../infiles/stellar_eqtide/ctl"
input_fix:
  "vpl.dStopTime":
    units: "u.Myr"
    true_value: 10
    label: r"age [Myr]"
input_var:
  "primary.dMass":
    units: "u.Msun"
    bounds: (0.6, 1.1)
    label: r"$\rm M_1 [M_{\odot}]$"
  "secondary.dMass":
    units: "u.Msun"
    bounds: (0.6, 1.1)
    label: r"$\rm M_2 [M_{\odot}]$"
  "primary.dRotPeriod":
    units: "u.day"
    bounds: (0.1, 6.0)
    label: r"$\rm P_{rot1,i} [d]$"
  "secondary.dRotPeriod":
    units: "u.day"
    bounds: (0.1, 6.0)
    label: r"$\rm P_{rot2,i} [d]$"
  "secondary.dEcc": 
    units: "u.dimensionless_unscaled"
    bounds: (0.0, 0.5)
    label: r"$e_i$"
  "secondary.dOrbPeriod":
    units: "u.day"
    bounds: (0.1, 12.0)
    label: r"$\rm P_{orb,i} [d]$"
  "primary.dTidalTau":
    units: "u.dex(u.s)"
    bounds: (-4.0, 1.0)
    label: r"$\rm \log\tau_1$ [dex(s)]"
  "secondary.dTidalTau":
    units: "u.dex(u.s)"
    bounds: (-4.0, 1.0)
    label: r"$\rm \log\tau_2$ [dex(s)]"
output:
  "final.primary.RotPer":
    units: "u.day"
    label: r"$\rm P_{rot1,f} [d]$"
  "final.secondary.RotPer":
    units: "u.day"
    label: r"$\rm P_{rot2,f} [d]$"
  "final.secondary.OrbPeriod":
    units: "u.day"
    label: r"$\rm P_{orb,f} [d]$"
  "final.secondary.Eccentricity":
    units: "u.dimensionless_unscaled"
    label: r"$e_f$"
